site_name: LanpartyGoDS
site_description: A look into the past
site_url: https://lanpartygods.com
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/lanparty.png
  favicon: assets/infinity-solid.svg
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  generator: true
  social:
  - icon: simple/youtube
    link: https://www.youtube.com/watch?v=yDAfrsVHULg

#hooks:
#  - hooks/socialmedia.py

copyright: Copyright &copy; 2024 LanpartyGoDS

plugins:
  - search:
  - blog: 
      blog_dir: .
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      post_url_format: "{slug}"

  - tags:
      tags_file: tags.md
  - rss:
      match_path: "posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - git-committers:
      enabled: true
      repository: cybrwlf/lpg
      branch: main 
      token: !ENV GH_TOKEN
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true  

    