site_name: LanpartyGoDS.com
site_description: A look into the past
site_url: https://lanpartygods.com
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/site_logo.gif
  favicon: assets/infinity-solid.svg
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  generator: true
  social:
  - icon: simple/youtube
    link: https://www.youtube.com/watch?v=yDAfrsVHULg

copyright: Copyright &copy; 2024 LanpartyGoDS

plugins:
  - search
  - rss
  - blog: 
      blog_dir: .
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      post_url_format: "{slug}"
      authors_profiles: true
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
