authors:
  cybrwlf: 
    name: CybrWlf
    description: Veteran Member
    avatar:  ./authors/cybrwlf.jpg
    url: ../authors/cybrwlf/
    
  heller:
    name: Heller
    description: Member
    avatar: ./authors/heller.jpg
    url: ../authors/heller/

  abysal: 
    name: Abysal
    description: Veteran Member
    avatar:  ./authors/abysal.jpg
    url: ../authors/abysal/

  doomxexec311:
    name: DoomXexec311
    description: Member
    avatar: ./authors/doomxexec311.jpg
    url: ../authors/doomxexec311/

  cyberfirex:
    name: CybrFireX
    description: Veteran Member
    avatar:  ./authors/circle-user-regular.svg
    url: ../authors/cyberfirex/

  flux: 
    name: Flux
    description: Veteran Member
    avatar:  ./authors/flux.jpg
    url: ../authors/flux/
    